### ISSUE TITLE
Не подключены шрифты

### ISSUE THREAD

**Issue by in19farkt** [Frolikow/resume#1]

**Comment by in19farkt** [comment]
не правильно подключены шрифты, браузер не знает как ты назвал подключенный шрифт. Еще не понял зачем ты выставил на `resume_education_li-univer` шрифт `Courier`.

**Comment by Frolikow** [comment]
подключил весь набор, добавил название в каждом font-face'е.
на счет **resume_education_li-univer** шрифт взял также как PSD был.
