### ISSUE TITLE
Каждый скилл сделать блоком

### ISSUE THREAD

**Issue by prodderman** [Frolikow/resume#13]
И добавить возможность передавать общее количество кружков и количество закрашенных кружков.
https://github.com/Frolikow/resume/blob/master/src/modules/skills/skills-mixin.pug

**Comment by prodderman** [comment]
и этого тоже касается https://github.com/Frolikow/resume/blob/master/src/modules/software/software-mixin.pug

**Comment by prodderman** [comment]
А еще у тебя опять модификатор отдельно от элемента
https://github.com/Frolikow/resume/blob/1501271f82689c711fd73081bfb65a6c8c05c7bf/src/modules/software/software-element/software-element.pug#L3-L5
Модификаторы должны модифицировать сам элемент, а у тебя они слишком самостоятельные.

**Comment by chmnkh** [comment]
1) В experience и education забыл передачу данных добавить
2) такие вот вещи: 
```
+software({name: 'photoshop', percentValue: 95})
+software({name: 'dreamweaver', percentValue: 85})
+software({name: 'illustrator', percentValue: 75})
```
лучше блоком тоже объединить, а не писать эту кучу вызовов миксинов в резюме.

**Comment by chmnkh** [comment]
Каждый скилл-то теперь не отдельный блок, как и софтвар)
