### ISSUE TITLE
Верстка не по БЭМу

### ISSUE THREAD

**Issue by in19farkt** [Frolikow/resume#2]
Блок это какая-то самодостаточная сущность, которую я без проблем смогу скопипастить в любое место и она будет адекватно отображаться, Элемент это часть блока, которая не имеет никакого смысла вне блока, Модификатор это состояние Блока или Элемента, может переопределять или дополнять стили Блока или Элемента. Названия блоков и элементов должны отвечать на вопросы "Кто? Что?", названия модификаторов в большинстве случаев отвечают на вопрос "Какой?" и иногда содержит название модифицируемого параметра. Избегай бессмысленных имен типа "block" или "element", старайся заменять их чем-то более осмысленным.

Схема именования классов следующая: `block__element_color-red` или просто `block__element_red`. 

Блоки могут содержать в себе другие независимые блоки, элемент может быть одновременно блоком. Например может быть такая структура:
```
header
└─ header__menu_left
└─── menu
└───── menu__button
└───── menu__button
└─ header__logo
```
здесь у блока `header` есть элемент `menu` внутри которого находится независимый блок `menu`.

**Comment by Frolikow** [comment]
поправил классы, мне кажется не шибко изменения получились) скажи на моем коде, где я нормально сделал, а где плохо) я исправлю)

**Comment by Frolikow** [comment]
проверь еще раз БЭМ )

**Comment by Geksanit** [comment]
`resume__column` - элемент правильно
`resume__columnLeft` - модификатор не правильно
`titleContent` - имя блока не правильно
проверь все классы

**Comment by chmnkh** [comment]
candidate__photo_inside
Почему на данном элементе именно такой класс? Что за элемент photo, и как его "модифицирует" модификатор inside? Почему элемент photo содержит сам себя?

**Comment by chmnkh** [comment]
```
.contact__table-column_data address
.contact__table-column_data e-mail
```
Те же самые вопросы (из предыдущего сообщения), кроме последнего.

**Comment by Frolikow** [comment]
[#25](https://github.com/Frolikow/resume/issues/25)

**Comment by chmnkh** [comment]
```
.softwares__scale
    .softwares__scale_filled(style = "width:" + item.percentValue + "%;")
```
Такого не должно быть. Обычно как: есть класс элемента, на нем стили, и класс модификатора, который эти стили дополняет или меняет какие-то из них, за счет этого кастомизация блока/элемента происходит. И чтобы это все работало на самой ноде должно 2 класса быть, вот так: 
```
.softwares__scale.softwares__scale_filled
```
Плюс ситуация, когда у тебя элемент содержит сам себя, немного странная. И если бы ты как раз расставил классы как нужно, то ты бы увидел, что элементы-то разные :)

**Comment by Geksanit** [comment]
![image](https://user-images.githubusercontent.com/31949379/45216891-555c8780-b2cc-11e8-8135-20c603b9c361.png)
Судя по классам при вызове миксина будет создан двойственный блок. Убери это дублирование.
стили в education.styl ничего не должны знать о внутреннем устройстве common-list

**Comment by Geksanit** [comment]
воспользуйся модификаторами или миксами

**Comment by Geksanit** [comment]
закрывай это ишью
