### ISSUE TITLE
Называть блоки и элементы по смыслу, а не по внешнему виду

### ISSUE THREAD

**Issue by chmnkh** [Frolikow/resume#21]
```
.candidate-photo__inside-circle
```
А если я его квадратным захочу сделать, мне придется класс менять?)

**Comment by chmnkh** [comment]
```
span.profile__content_bold
```
Здесь не исправил.
Я понимаю, что тут может быть не совсем понятно, что там именно жирным выделяется, но постарайся что-то придумать :)

**Comment by chmnkh** [comment]
К модификаторам так же относится:
```
li.skill__value.skill__value_color_blue
```

**Comment by Frolikow** [comment]
Почему-то коммит не отображается в ишью. [Добавляю так](https://github.com/Frolikow/resume/commit/0a0a67184a4ad66b8040f45cb7558374f8630aee)

**Comment by chmnkh** [comment]
А что значит scale и filler? Что ты хотел сказать (по-русски)?)

**Comment by Frolikow** [comment]
scale - шкала, а filler - наполнитель)

**Comment by chmnkh** [comment]
а почему каждый скилл поинт - это шкала? я бы еще понял, если бы ты как-то их совокупность шкалой назвал (мне не очень нравится, но понять можно), а каждый отдельный скилл поинт называть шкалой - странно
про filler: тут уже тупо часть речи не та, чтобы модификатором это делать :)
почитай у нас в стандартах пункт про именование модификаторов в разделе БЭМа у CSS

**Comment by Frolikow** [comment]
На счет scale- сглупил если честно) поправил по-логичнее)
