### ISSUE TITLE
Все размеры в пикселях

### ISSUE THREAD

**Issue by in19farkt** [Frolikow/resume#3]
Почитай про единицы измерения в верстке и не используй пиксели. Если у тебя все будет в rem-ах, то изменив высоту шрифта у одного элемента, ты сможешь изменить масштаб всей верстки, например для маленьких экранов мобильных телефонов.

**Comment by in19farkt** [comment]
Не, так не пойдет))) На html ставится стандартный размер шрифта 14-16px.

**Comment by Frolikow** [comment]
блин)это вроде как стандарт, да?

**Comment by in19farkt** [comment]
Ага)

**Comment by Frolikow** [comment]
исправил)

**Comment by Geksanit** [comment]
осталось ещё одно место с пикселями вот тут
`html{
  font-size: 31px;`
