### ISSUE TITLE
Education и experience 

### ISSUE THREAD

**Issue by chmnkh** [Frolikow/resume#33]
Если посмотреть на эти блоки внимательно, то можно увидеть, что там явно можно что-то переиспользовать :)

**Comment by Frolikow** [comment]
Если я правильно понял, то кажется я переделал в другом [ишью](https://github.com/Frolikow/resume/commit/2e31fc8be143ea355dfb5b3fced5b9089b29474e) )

**Comment by chmnkh** [comment]
Посмотри на education и experience и на education-item и experience-item в коде и на макете.
У тебя там идентичные блоки и просто 2 раза одно и то же написано фактически с небольшими изменениями :)

**Comment by chmnkh** [comment]
Тут же сразу напишу:
если ты выделяешь, например, eduation(experience)-item или skill в отдельные блоки, то они должны лежать в папке с блоками, а не в папках других блоков.

**Comment by chmnkh** [comment]
Идея правильная, но не круто, что у тебя стили для этого листа и классы блоков/элементов как-то  извне навязываются. Это все нужно в рамках самого блока задать, а передавать только данные и модификаторы для кастомизации.

**Comment by Frolikow** [comment]
similar - похожий,схожий,аналогичный) мне показалось это логичным) хотя теперь кажется лучше назвать common-list )

**Comment by Geksanit** [comment]
![image](https://user-images.githubusercontent.com/31949379/45217730-5c38c980-b2cf-11e8-8f2d-4c2bb11c19ed.png)
Судя по классам при вызове миксина будет создан двойственный блок. Убери это дублирование.
Стили в education.styl и experience.styl ничего не должны знать о внутреннем устройстве common-list

**Comment by Geksanit** [comment]
закрывай ишью
