### ISSUE TITLE
косметические правки

### ISSUE THREAD

**Issue by Geksanit** [Frolikow/resume#35]
в candidate.bug `+avatar({image:`${imageUrl}`})` - imageUrl и так строка
поправь code style: не хватает пробелов до/после  `=`, пробелов в деструктуризации объектов

**Comment by Geksanit** [comment]
относись к pug коду как к js коду

**Comment by Frolikow** [comment]
@Geksanit 
> относись к pug коду как к js коду

Не совсем понял, что ты имеешь ввиду. Поясни пожалуйста
