### ISSUE TITLE
Вертикальное выравнивание переделать без хардкода

### ISSUE THREAD

**Issue by Znack** [Frolikow/resume#36]
Сейчас там у полоски выравнивание "margin-top: 1.875rem", а надо, чтобы не было никакого хардкода конкретного отсупа, отсупы должны вычисляться автоматом, чтобы для каждого размера шрифта не приходилось считать

**Comment by Frolikow** [comment]
[#36](https://github.com/Frolikow/resume/commit/31e6e03b0956b3a18eaaf2d1ccfb255816c95118)

**Comment by Frolikow** [comment]
> Можешь плиз еще страницы на github обновить, чтобы я там глянул?

Обновил)
