### ISSUE TITLE
Верстка не респонсивна

### ISSUE THREAD

**Issue by in19farkt** [Frolikow/resume#4]
Верстка должна быть максимально респонсивной, при уменьшении ширины области просмотра до 320px не должен появляться горизонтальный скрол, при этом страничка должна выглядеть адекватно.

**Comment by Geksanit** [comment]
ишью всё ещё актуален.

**Comment by chmnkh** [comment]
У тебя примерно на 700 с копейками сейчас уже скролл появляется, + в одной колонке верхние блоки (до skills включительно) уже нижних, некрасиво выглядит.

**Comment by Geksanit** [comment]
закрывай ишью
