### ISSUE TITLE
Не использовать картинки там, где они не нужны (не усложнять, где не надо)

### ISSUE THREAD

**Issue by chmnkh** [Frolikow/resume#6]
Не сильно щедро будет точку лист айтему выставлять бэкграундом?)

**Comment by Frolikow** [comment]
Исправил. Ветка: 
https://github.com/Frolikow/resume/tree/t6_Do_not_use_pictures_where_they_are_not_needed

**Comment by chmnkh** [comment]
а почему в отдельной ветке сделал?

**Comment by Frolikow** [comment]
В стандартах прочитал, что для каждого ишью отдельную ветку делать.

3.Создаем ветку для этого issue по паттерну: t123_issue_short_name (t - это префикс, всегда начинать название с него, 123 это номер issue, issue_short_name - короткое название issue, которое придумывает создатель ветки из содержания issue)

**Comment by chmnkh** [comment]
В рамках тестового задания в этом необходимости нету, раз уж ты начал рефакторинг в мастер ветке, в нее и продолжай все лить, просто ссылайся ни ишью в сообщении коммита и все.

**Comment by chmnkh** [comment]
То есть кусок стандартов по гиту вообще для тестового задания не актуален, не него вообще не стоит как-то сейчас ориентироваться.

**Comment by Frolikow** [comment]
> То есть кусок стандартов по гиту вообще для тестового задания не актуален, на него не стоит как-то сейчас ориентироваться.

Это касательно только данного задания или всех?

**Comment by chmnkh** [comment]
Для всех заданий.
Тут ты над каждым проектом один работаешь, и поэтому все то что там описано особого смысла не имеет)

**Comment by Frolikow** [comment]
Понял)

**Comment by chmnkh** [comment]
На разных проектах некоторые детали отличаться могут, но в целом да.

**Comment by chmnkh** [comment]
Картинку удали и закрывай.
