### ISSUE TITLE
БЭМ. Модификатор не должен быть отдельно от блока/элемента

### ISSUE THREAD

**Issue by prodderman** [Frolikow/resume#8]
https://github.com/Frolikow/resume/blob/7967c81640772883efe01f74c83471f2710c0dea/src/modules/candidate/candidate-mixin.pug#L7-L10
и еще много где по проекту

**Comment by prodderman** [comment]
и проверь по всему проекту, много где видел данный косяк.

**Comment by chmnkh** [comment]
Можешь закрыть.
